version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_DBPASS

  neutron:
    build:
      context: .
    image: openstack-neutron:ubuntu-pike-sfc
    depends_on:
      - mysql
    image: openstack-neutron:ubuntu-pike-sfc
    hostname: neutron
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    ports:
      - 9696:9696
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /lib/modules:/lib/modules
      - /var/run/openvswitch:/var/run/openvswitch
      - /etc/openvswitch/conf.db:/etc/openvswitch/conf.db
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_DBPASS
      OS_TENANT_NAME: admin
      OS_USERNAME: admin
      OS_PASSWORD: password
      LOCAL_IP: ${LOCAL_IP}

#volumes:
#  shared:
#    driver: local 
